services:
  # backend:
  #   container_name: app
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     CONN_STR: goddit_app:insecure@tcp(db:3306)/goddit_db
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  mysql:
    container_name: goddit_db
    image: mysql
    # restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: insecure
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/1_setup.sql
      - ./db/initial_data.sql:/docker-entrypoint-initdb.d/2_initial_data.sql
      - ./db/create_db_user.sql:/docker-entrypoint-initdb.d/3_create_db_user.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pinsecure"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongodb:
    container_name: goddit_mongo
    image: mongo
    # restart: always
    ports:
      - "27017:27017"
    
volumes:
  db-data: