services:
  migrator:
    container_name: migrator
    build:
      context: .
    environment:
      MYSQL_CONN_STR: goddit_app:insecure@tcp(goddit:3306)/goddit
      MONGO_CONN_STR: mongodb://goddit_mongo:27017
    networks:
      - goddit-network

networks:
  goddit-network:
    external: true
